### ISSUE TITLE
quorum write/read bug

### ISSUE THREAD

**Issue by sfwang218** [Tencent/Firestorm#105]
<img width="837" alt="图片" src="https://user-images.githubusercontent.com/16055211/162911871-ce8373d5-bba1-4f3b-8941-6ee630bb48c2.png">
这段代码的逻辑感觉有问题啊，还是我的理解有问题？
正常不应该是判断 每一个 partition 成功 report 的次数 达到 replicaWrite 阈值时，才能算最终 report 成功么？
现在的逻辑判断的好像是，成功 report 的 shuffle server数 达到 replicaWrite 阈值时，就算是最终 report 成功。

**Comment by frankliee** [comment]
Each partition has _replica_ number of "instances" located on _replica_ number of servers.
Therefore, the report should be to  send to at least _replicaWrite_ number of servers.

**Comment by sfwang218** [comment]
举个例子吧，比如说某个 shuffle 操作分配了 5个 shuffle server，然后 spark.rss.data.replica 和 spark.rss.data.replica.write 设置的都是2，那就是说 对于每一个 partition，必须2个副本都report 成功了才算成功是吧，
那也就是说 5个 shuffle server 都必须 report 成功 才行。
但是按照上面的判断逻辑，只要超过2个 shuffle server report 成功的话，就不会抛异常。
不知道我理解的对不对，还请指正，多谢啦！

**Comment by sfwang218** [comment]
> Each partition has _replica_ number of "instances" located on _replica_ number of servers, respectively. Because the writer works in an asynchronous manner, at each time, "a group of instances" that assigned to a server are issued together. Therefore, the report should be to send to at least _replicaWrite_ number of servers, which means each server has received this group of instances.

举个例子吧，比如说某个 shuffle 操作分配了 5个 shuffle server，然后 spark.rss.data.replica 和 spark.rss.data.replica.write 设置的都是2，那就是说 对于每一个 partition，必须2个副本都report 成功了才算成功是吧，
那也就是说 5个 shuffle server 都必须 report 成功 才行。
但是按照上面的判断逻辑，只要超过2个 shuffle server report 成功的话，就不会抛异常。
不知道我理解的对不对，还请指正，多谢啦！

**Comment by frankliee** [comment]
Thanks for your issue, there is a PR to fix this.
You can review https://github.com/Tencent/Firestorm/pull/107

**Comment by sfwang218** [comment]
> Thanks for your issue, there is a PR to fix this. You could review #107

OK, Thanks

**Comment by jerqi** [comment]
Resovled by #107
