### ISSUE TITLE
Error with patch spark-3.1.2_dynamic_allocation_support.patch

### ISSUE THREAD

**Issue by avs-alatau** [Tencent/Firestorm#106]
Hi
I tried to apply this patch /spark-patches/spark-3.1.2_dynamic_allocation_support.patch for version 3.2.1
I get an error 
`[ERROR] [Error] /home/alatau/spark-3.2.1-src/sql/core/src/main/scala/org/apache/spark/sql/execution/ShuffledRowRDD.scala:180: wrong number of arguments for pattern org.apache.spark.sql.execution.CoalescedPartitionSpec(startReducerIndex: Int,endReducerIndex: Int,dataSize: Option[Long])`

180: _case CoalescedPartitionSpec(startReducerIndex, endReducerIndex) =>_

Can you help with fixing the patch for version 3.2.1 ?

**Comment by colinmjj** [comment]
Thanks for report, the patch is only target to spark 3.1.2, the patch for 3.2.1 will be available in next release（may be end of April）

**Comment by cpd85** [comment]
@colinmjj any updates on ETA here?

**Comment by colinmjj** [comment]
@jerqi can you help to add the patch for spark 3.2?

**Comment by jerqi** [comment]
> @jerqi can you help to add the patch for spark 3.2?

ok

**Comment by jerqi** [comment]
solved by #199
