### ISSUE TITLE
coordinator不需要是高可用的吗

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#109]
看shuffleWriteClientImpl的getShuffleAssignment方法就是遍历coordinatorClients，请求成功则返回分配结果，这似乎没有做到coodinator的负载均衡 ？

**Comment by jerqi** [comment]
Load balance isn't necessary here.

**Comment by xunxunmimi5577** [comment]
那这样不是只会去请求第一个coordinator吗？

**Comment by jerqi** [comment]
Yes

**Comment by xunxunmimi5577** [comment]
Ok, GOT it. Thank you
