### ISSUE TITLE
What is the role of configuration "spark.rss.writer.buffer.segment.size"

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#114]
The property called `buffers`  in the class `WriterBuffer`  is a list of WrappedBuffers. What does it do?
getData() eventually returns byte[] for all data, so why fragment it beforehand?

**Comment by jerqi** [comment]
We don't know the total size of data at first.

**Comment by xunxunmimi5577** [comment]
Can we directly define the length of `WriterBuffer.buffer` as "spark.rss.writer.serializer.buffer.size"?

**Comment by jerqi** [comment]
> Can we directly define the length of `WriterBuffer.buffer` as "spark.rss.writer.serializer.buffer.size"?

If we have many partitions, that will waste too many memory.

**Comment by xunxunmimi5577** [comment]
Ok, GOT it. Thank you
