### ISSUE TITLE
Whether multiple disks are supported for local storage？

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#120]

**Comment by colinmjj** [comment]
Yes, shuffle data will be written to different local disk according to partition.

**Comment by xunxunmimi5577** [comment]
How to configure multiple disks?

**Comment by colinmjj** [comment]
rss.storage.basePath  /path1,/path2,/path3

**Comment by xunxunmimi5577** [comment]
ok，Thank you！
