### ISSUE TITLE
What‘s the difference  between `spark.rss.storage.type` and `rss.storage.type`?

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#127]

**Comment by jerqi** [comment]
`spark.rss.storage.type` is client's configuration.`rss.storage.type` is server's configuration.

**Comment by xunxunmimi5577** [comment]
Both parameters affect the storage mode of ShuffleServer？ Then，which one has a higher priority?

**Comment by jerqi** [comment]
> Both parameters affect the storage mode of ShuffleServer？ Then，which one has a higher priority?
Only `rss.storage.type` affects.

**Comment by xunxunmimi5577** [comment]
What is `spark.rss.storage.type` used for？

**Comment by jerqi** [comment]
> What is `spark.rss.storage.type` used for？

client

**Comment by xunxunmimi5577** [comment]
Does the client also can store data to a local disk or HDFS?

**Comment by jerqi** [comment]
> Does the client also can store data to a local disk or HDFS?

Client need to know where to read data.

**Comment by xunxunmimi5577** [comment]
So these two parameters need be set to the same?

**Comment by jerqi** [comment]
> So these two parameters need be set to the same?

Yes

**Comment by xunxunmimi5577** [comment]
ok,thanks

**Comment by xunxunmimi5577** [comment]
I have a problem,when I set storageType = HDFS, Error: Blocks read Inconsistent: Expected 61 Blocks, actual 0 Blocks
The version I'm using is 0.2.0

**Comment by xunxunmimi5577** [comment]
The configuration items are as follows
rss.rpc.server.port 19969
rss.jetty.http.port 19968
rss.storage.basePath /rss-0.2.0/shuffle-data1,/rss-0.2.0/shuffle-data2
rss.storage.type HDFS
rss.coordinator.quorum xxx:19999,xxx:19999,xxx:19999
rss.server.buffer.capacity 4gb
rss.server.buffer.spill.threshold 2gb
rss.server.partition.buffer.size 15mb
rss.server.read.buffer.capacity 2gb
rss.server.flush.thread.alive 5
rss.server.flush.threadPool.size 10
rss.server.health.check.enable false

# multistorage config
rss.server.multistorage.enable true
rss.server.uploader.enable true
rss.server.uploader.base.path hdfs:/firestorm/shuffle-data
rss.server.uploader.thread.number 3
rss.server.disk.capacity 5115506975

Spark client
spark.shuffle.manager org.apache.spark.shuffle.RssShuffleManager
spark.rss.coordinator.quorum xxx:19999,xxx:19999,xxx:19999
spark.rss.storage.type HDFS

**Comment by jerqi** [comment]
We don't recommend the storageType HDFS, you would better to use MEMORY_LOCALE.

**Comment by jerqi** [comment]
Storage HDFS will be removed soon.

**Comment by xunxunmimi5577** [comment]
Is there some problems with HDFS storage mode, so you want to remove it?

**Comment by xunxunmimi5577** [comment]
In terms of the results of my tests,  only when I set storage type = LOCALFILE_HDFS that the shuffle data will be written to HDFS.
But I also find, in this case，if I delete local data, the same exception 'Blocks read Inconsistent' is reported,  so i want to figure out if the function of reading shuffle data from HDFS is not sound enough so far.
Thanks for your time！

**Comment by jerqi** [comment]
> Is there some problems with HDFS storage mode, so you want to remove it?

HDFS mode have poor performance. HDFS can work correctly.

**Comment by xunxunmimi5577** [comment]
> > Is there some problems with HDFS storage mode, so you want to remove it?
> 
> HDFS mode have poor performance. HDFS can work correctly.

Yes, you're right. I've got some configurations set incorrectly.
