### ISSUE TITLE
In local mode, why directory should be deleted first？

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#132]
In class LocalStorage：

```java
File baseFolder = new File(basePath);
    try {
      FileUtils.deleteDirectory(baseFolder);
      baseFolder.mkdirs();
    } catch (IOException ioe) {
```

What if the disk cannot be deleted？

**Comment by jerqi** [comment]
If a server crash suddenly, there are some shuffle files in that directory. So when we start a shuffle server, we delete these shuffle files first.
