### ISSUE TITLE
[QUESTION] 依赖Hadoop环境？

### ISSUE THREAD

**Issue by fuhaiq** [Tencent/Firestorm#133]
我看到需要配置一个HADOOP_HOME环境变量，Firestorm只能在hadoop环境下部署么？有没有配置可以关掉？

**Comment by jerqi** [comment]
目前是依赖HADOOP环境，目前没有一个配置开关可以关掉。

**Comment by colinmjj** [comment]
@fuhaiq 理论上使用 Memory_Local模式的话, 可以不需要Hadoop环境，但这块目前有待优化并剥离

**Comment by fuhaiq** [comment]
谢谢大家的回答
