### ISSUE TITLE
[Feature Request]Add a web UI in Coordinated Server to show the detailed server/job/metrics information

### ISSUE THREAD

**Issue by jerryshao** [Tencent/Firestorm#136]
It would be good to have a web UI in coordinated server to show the detailed information about shuffle server, job shuffle metrics and others. Simply like Spark web UI which has the ability to show the detailed information of Spark jobs.

**Comment by advancedxy** [comment]
> It would be good to have a web UI in coordinated server to show the detailed information about shuffle server, job shuffle metrics and others. Simply like Spark web UI which has the ability to show the detailed information of Spark jobs.

+1 for this. It's super helpful when debugging shuffle performance problems. Along side the coordinated server, the shuffle sever itself could also have a web UI to expose more observability.
