### ISSUE TITLE
Compared to the native spark, the shuffle write data of firestorm is always smaller

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#157]
Due to company's security restrictions,I cannot upload images. Let me describe the phenomenon simply , for the same stage of the same SQL, the value of `Shuffle Write Size/Records`  are 16 B/1 and 58 B/1 respectively? The former is the result from firestorm

**Comment by jerqi** [comment]
Firestorm will compress data.

**Comment by xunxunmimi5577** [comment]
ok，I see，thank you!
