### ISSUE TITLE
Unexpected crc value for blockId[474989042101783], expected:1518107711, actual:3331113690

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#166]
What usually causes this error？

**Comment by jerqi** [comment]
What's your version? You can reproduce this error stably? This error means that some shuffle data is wrong.

**Comment by xunxunmimi5577** [comment]
My version is 0.2.0 and I've tried three times，it happens every time

**Comment by colinmjj** [comment]
@xunxunmimi5577 I think it may be caused by the bug which is fixed in https://github.com/Tencent/Firestorm/pull/92

**Comment by xunxunmimi5577** [comment]
> @xunxunmimi5577 I think it may be caused by the bug which is fixed in #92
Ok,I agree,thank you!

**Comment by jerqi** [comment]
It' not active for 7 days, I will close it.
