### ISSUE TITLE
spark.rss.storage.type 三种部署类型性能有差异吗？

### ISSUE THREAD

**Issue by melin** [Tencent/Firestorm#17]
LOCALFILE, HDFS, LOCALFILE_AND_HDFS 三种部署类型性能有差异吗？有测试数据？

**Comment by colinmjj** [comment]
@melin according to the test, the different of three storage mode:
1. LocalFile: shuffle data is stored in disk of shuffle server. The bottleneck is diskIO, Firestorm can work fine when disk IO > shuffle data generate ratio.
2. HDFS: shuffle data is stored in HDFS. The bottleneck is stability of HDFS, especially with high workload.
3. LOCALFILE_AND_HDFS: it's an experimental feature which is target to store data in HDFS when local disk is full.
Suggest to start with LocalFile mode for stability and the performance is related diskIO.
