### ISSUE TITLE
Shuffle read does not read all data completely?

### ISSUE THREAD

**Issue by xunxunmimi5577** [Tencent/Firestorm#175]
When running query64 of tpcds 10T data，Ifind a stage have shuffle wrote 1.3T of data,but I never find a stage which reads 1.3T of data accordingly.

**Comment by colinmjj** [comment]
Can you share the spark UI for stage IO?

**Comment by xunxunmimi5577** [comment]
Compared to the native Spark, Shuffle Write has the same amount of data, but Firestorm reads very little data during Shuffle Read. The label `Task:Succeeded/Total` in spark ui shows only one Task in Firestorm，but Spark shows 5000 tasks are successfully executed.

**Comment by colinmjj** [comment]
How about the result?  Is it the same as the result with native Spark?
we passed result compare based on 1TB data, but haven't did this with 10TB data.

**Comment by xunxunmimi5577** [comment]
![Uploading IMG_20220615_092133.jpg…]()

**Comment by xunxunmimi5577** [comment]
![Uploading IMG_20220615_092112.jpg…]()

**Comment by xunxunmimi5577** [comment]
> How about the result? Is it the same as the result with native Spark? we passed result compare based on 1TB data, but haven't did this with 10TB data.

I need to confirm this, because we modified the SQL and did not collect the results

**Comment by xunxunmimi5577** [comment]
Does Firestorm print partition lengths to MapStatus？

**Comment by jerqi** [comment]
We record the length, aqe need the metrics.

**Comment by xunxunmimi5577** [comment]
I find that when I use aqe ,I got the wrong statistics



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/21/2022 11:47 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [Tencent/Firestorm] Shuffle read does not read all data completely? (Issue #175) |

We record the length, aqe need the metrics.

**Comment by jerqi** [comment]
Could you give me more detail information?

**Comment by xunxunmimi5577** [comment]
Firestorm for spark2 does‘t support AQE？I saw that the implementation of the stop() method in RssShuffleWriter(Spark2) seems to fill the partitionLengthse with dummy value.

**Comment by xunxunmimi5577** [comment]
However spark2 do support this configuration `spark.sql.crossJoin.enabled`. If as mentioned above,then `spark.sql.crossJoin.enabled` can't be set to true?

**Comment by jerqi** [comment]
> Firestorm for spark2 does‘t support AQE？I saw that the implementation of the stop() method in RssShuffleWriter(Spark2) seems to fill the partitionLengthse with dummy value.

spark2 don't support AQE.

**Comment by jerqi** [comment]
The open source Spark2 don't support AQE, too.

**Comment by xunxunmimi5577** [comment]
> > Firestorm for spark2 does‘t support AQE？I saw that the implementation of the stop() method in RssShuffleWriter(Spark2) seems to fill the partitionLengthse with dummy value.
> 
> spark2 don't support AQE.

But if I set `spark.sql.adaptive.enabled=true`，I will get the wrong result.

**Comment by xunxunmimi5577** [comment]
As far as I know, spark2 can also use configuration `spark.sql.adaptive.enabled`.

**Comment by xunxunmimi5577** [comment]
Then ExchangeCoordinator.doEstimationIfNecessary() method will need mapOutputStatistics to determine the number of post-shuffle partitions.

**Comment by jerqi** [comment]
It's not available feature in Spark2. Maybe some configurations were added first , but the implement isn't complete.

**Comment by xunxunmimi5577** [comment]
If I use spark2 + firestorm + `spark.sql.adaptive.enabled=true`, partitionStartIndices from ExchangeCoordinator will be [0,200) instead of [0,1),[1,2),... ,then shuffleReader will only read partition 0，this is the phenomenon described in my issue，there were supposed to be 200 tasks to execute, but only one was executed.
I think users should at least be prompted of this.

**Comment by colinmjj** [comment]
@xunxunmimi5577 thanks for report this, I think it should be described in readme for such unsupported case.

**Comment by jerqi** [comment]
> > > If I use spark2 + firestorm + `spark.sql.adaptive.enabled=true`, partitionStartIndices from ExchangeCoordinator will be [0,200) instead of [0,1),[1,2),... ,then shuffleReader will only read partition 0，this is the phenomenon described in my issue，there were supposed to be 200 tasks to execute, but only one was executed. I think users should at least be prompted of this.
> > 
> > 
> > OK, We can check whether ADAPTIVE_EXECUTION_ENABLED is enabled in RssShuffleManager. If true, we can throw an illegal argument exception. Would you like to contribute it?
> 
> I would like to, or maybe you just want to describe it in readme？

Actually,  we want to do two things. We want to add the parameter check in code. And we also want to increase document description.

**Comment by jerqi** [comment]
> Moreover, is it possible to record an array of partitionLengths like Spark3?

It's not available Feature in Spark 2. We wouldn't do it.

**Comment by xunxunmimi5577** [comment]
OK

**Comment by jerqi** [comment]
Could I close this issue? Is it solved?

**Comment by xunxunmimi5577** [comment]
I think it's solved.Let me close this issue.
