### ISSUE TITLE
Support shuffle data replica?

### ISSUE THREAD

**Issue by zuston** [Tencent/Firestorm#181]
Thanks for your great work on it.

I have a question that I dont see any info about data replica support in README or other doc. But i see the config in codebase. 

So the data replica is stable feature in firestorm?

**Comment by zuston** [comment]
And what's the difference of the config of data-replica and data-replica-writer ?

**Comment by frankliee** [comment]
These configs are come from quorum protocol.
`rss.data.replica` is replica number of partition.
`rss.data.replica.write` is the minimum replica that writer should write metadata and data successfully. 
`rss.data.replica.read` is the minimum replica that reader should read metadata successfully. 
The recommended values are (1,1,1) and (3,2,2),
This feature has been developed completely, but production environment only applies (1,1,1) to reduce rpc/memory cost.

**Comment by zuston** [comment]
Thanks for your explanation @frankliee.

So the data replica will be supported through client pushing instead of shuffle server.

**Comment by frankliee** [comment]
> Thanks for your explanation @frankliee.
> 
> So the data replica will be supported through client pushing instead of shuffle server.

Yes, its client-side feature.

**Comment by zuston** [comment]
Thanks again. @frankliee 

Close it.
