### ISSUE TITLE
why not delete shuffle files when spark job finished?

### ISSUE THREAD

**Issue by wangyi2021** [Tencent/Firestorm#20]
In my opinion, it can reduce the cost of storage.

**Comment by jerqi** [comment]
Spark sometimes will reuse another job's exchange.

**Comment by wangyi2021** [comment]
> Spark sometimes will reuse another job's exchange.

Yes, a yarn task by spark-submit, called application, may has more than one job. So is there any way or idea to delete files after application finished?

**Comment by jerqi** [comment]
If an application finish, the shuffle server will delete the shuffle files In Firestorm.
