### ISSUE TITLE
shuffle write is too slow

### ISSUE THREAD

**Issue by packageman** [Tencent/Firestorm#35]
When I use firestorm as the external shuffle service, I found that the execution of spark tasks(with 2 executors, 2c4g resource limit for each) using firestorm is much slower than using the built-in spark shuffle service. You can see through spark UI, mainly because the shuffle write time is too large.

With built-in shuffle service:

![image](https://user-images.githubusercontent.com/12949466/145969993-46841a44-27a3-4cc8-bc6c-5cc8cf90d1e8.png)

With firestorm:

![image](https://user-images.githubusercontent.com/12949466/145959544-9bf0c98c-c31f-4ddf-a540-c12da240e3db.png)

I added some debugging code to the logic of firestorm writing shuffle data to the shuffle server. For example, the 2294 task in the screenshot, shuffle write takes 47ms, of which:

- [`requirePreAllocation`](https://github.com/Tencent/Firestorm/blob/master/internal-client/src/main/java/com/tencent/rss/client/impl/grpc/ShuffleServerGrpcClient.java#L220) takes 2ms
- [`sendShuffleData`](https://github.com/Tencent/Firestorm/blob/master/client/src/main/java/com/tencent/rss/client/impl/ShuffleWriteClientImpl.java#L99) takes 3ms
- [`executor.submit`](https://github.com/Tencent/Firestorm/blob/master/client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java#L240) takes 31 ms
- [`sendCommit`](https://github.com/Tencent/Firestorm/blob/master/client/src/main/java/com/tencent/rss/client/impl/ShuffleWriteClientImpl.java#L174) takes 2ms

From spark logs I found these stats:

```
{"type":"service","category":"org.apache.spark.shuffle.writer.RssShuffleWriter","level":"info","message":"Finish write shuffle for appId[spark-94d48661c6ff4b9f8f83ef860a509ee61639469487297], shuffleId[33], taskId[2294_0] with write 42 ms, include checkSendResult[6], commit[36], WriteBufferManager cost copyTime[0], writeTime[0], serializeTime[0], compressTime[0], estimateTime[0], requireMemoryTime[0], uncompressedDataLen[528]","context":{},"reqId":"d20a2b6c-042c-4697-aad5-484455ca6cb7"}
```

Below are coordinator and shuffle server configurations(with 1 coordinator and 1 shuffle server instance for testing)

```shell
# java -versioon
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

`rss-env.sh`

```shell
set -o pipefail
set -e
XMX_SIZE="2g"
RUNNER="${JAVA_HOME}/bin/java"
JPS="${JAVA_HOME}/bin/jps"
```

`coordinator.conf`

```shell
rss.rpc.server.port 19999
rss.jetty.http.port 19998
rss.coordinator.server.heartbeat.timeout 30000
rss.coordinator.app.expired 60000
rss.coordinator.shuffle.nodes.max 13
rss.coordinator.exclude.nodes.file.path /data/exclude_nodes
```

`server.conf`

```shell
rss.rpc.server.port 20001
rss.jetty.http.port 20000
rss.storage.basePath /data/rss
rss.storage.type LOCALFILE
rss.coordinator.quorum xxx:19999
rss.server.buffer.capacity 40gb
rss.server.buffer.spill.threshold 22gb
rss.server.partition.buffer.size 150mb
rss.server.read.buffer.capacity 20gb
rss.server.flush.thread.alive 50
rss.server.flush.threadPool.size 100
```

Compared with the built-in shuffle service, the task execution time is more than 3 times higher. Please see the reason for the slow shuffle write.

**Comment by jerqi** [comment]
In our production environment,  the size of shuffle is usually hundreds of GBs. For very small shuffles, Firestorm will be slower than native shuffles. But there seems to be room for optimization. If you are interested in this, you can contribute it.

**Comment by colinmjj** [comment]
@packageman with firestorm, there are some RPC calls to send data, as you mentioned, requirePreallocation etc.  Your case is the same as we expected, with small shuffle data, Firestorm will be a little slower than origin shuffle.
For reference, Firestorm is target to :
1. Support Spark on K8s things
2. Improve job's performance/stability with heavy shuffle workload, eg, shuffle data = TB, partition num = 50000+

**Comment by packageman** [comment]
> Support Spark on K8s things

Currently, we are running Spark on k8s.

![image](https://user-images.githubusercontent.com/12949466/146130015-d870f5b8-edfd-4e87-86d3-fc3ddfaedbd0.png)

> with small shuffle data, Firestorm will be a little slower than origin shuffle

It looks not only a little slower but also a lot slower(2mins vs 5.6mins), nearly 2 times. I understand that grpc call will take some extra time, but the total time is more than double that of the native shuffle when working with small shuffle data, which is not consistent with your description.

with native shuffle:

![image](https://user-images.githubusercontent.com/12949466/146121005-422ce2f8-7493-4ade-a89c-b96bda01635e.png)

with Firestorm:

![image](https://user-images.githubusercontent.com/12949466/146130382-fe3f1cef-f563-4043-9873-3e8a9c982824.png)

**Comment by colinmjj** [comment]
@packageman with your case, 1W+task total, the delay should be depend on task number of parallels, if every task is slower about 0.5s with Firstorm, then 
1. 1W parallels task should be slower 0.5s total
2. 1000  parallels task should be slower 5s total
3. 100 parallels task should be slower 50s total
It's the behave we known, Firstorm is not target to improve performance with any situation. Platform can decide if use Firestorm with all Spark job, or with specific job.
From your case, input data for every task is less than 1MB, shuffle write data is less than 1kb. Optimize job to have more data for every task will be better.
