### ISSUE TITLE
请问出于什么考虑， coordinator没有使用常见的注册服务(zk, etcd, ...)?

### ISSUE THREAD

**Issue by mggger** [Tencent/Firestorm#70]
uber的rss基于zookeeper注册活跃的实例,    京东的rss基于etcd做元数据管理

**Comment by colinmjj** [comment]
In Firestorm, Coordinator take the responsibility to find Shuffle Server, I think it is the same as zk in uber and etcd in JD's rss. With coordinator, extra function can be added, eg, get metrics, assignment strategy, monitor Shuffle server's status etc.
