### ISSUE TITLE
"Blocks read inconsistent" happened when shuffle read 

### ISSUE THREAD

**Issue by Augus-smile** [Tencent/Firestorm#76]
你好， 我在执行spark 作业时， 在shuffle read阶段，显示blocks read inconsistent错误， 请问是什么原因呢？

server.conf:

rss.server.flush.thread.alive=2
rss.server.flush.threadPool.size=4
rss.server.buffer.capacity=6g
rss.server.read.buffer.capacity=3g
rss.server.disk.capacity=180g

server_rss_env.sh:
....
XMX_SIZE="12g"
....

**Comment by colinmjj** [comment]
When shuffle read, after process all block, it will check if all expected blocks are processed. "Blocks read inconsistent" will be thrown when some blocks are lost. It maybe caused by failed when write shuffle data.

**Comment by Augus-smile** [comment]
Thank you for your reply, Does the LOCALFILE_AND_HDFS mode write data to the HDFS and Shuffle server at the same time?

**Comment by Augus-smile** [comment]
Shuffle server process was killed due to OOM, related server conf : physical memory : 16g, XMX_SIZE:  12g. However, during the Spark task execution, the Shuffle Server process occupies nearly 16g memory.  What are the memory consumption components of the Shuffle Server? Is there a parameter to restrict the memory usage of shuffle Server?

**Comment by Augus-smile** [comment]
Sorry , Indeed set XMX_SIZE="12g" in rss_env.sh 
rss_env.sh : 
JAVA_HOME=${MY_JAVA_HOME}
HADOOP_HOME=${MY_HADOOP_HOME}
XMX_SIZE="12g"
RUNNER="${JAVA_HOME}/bin/java"
JPS="${JAVA_HOME}/bin/jps"
