### ISSUE TITLE
Any plans to support run on K8S？

### ISSUE THREAD

**Issue by fishcus** [Tencent/Firestorm#90]
any plans to support run on K8S？

**Comment by colinmjj** [comment]
yes, we plan to add k8s support in next release.

**Comment by fishcus** [comment]
> yes, we plan to add k8s support in next release.

when it will be released？

**Comment by colinmjj** [comment]
maybe in early April

**Comment by fishcus** [comment]
> maybe in early April

thanks for your prompt reply

**Comment by roryqi** [comment]
@fishcus We support to run on K8S, you can see https://github.com/apache/incubator-uniffle/issues/48
