### ISSUE TITLE
Storage path must be set by the client or fetched from coordinators.

### ISSUE THREAD

**Issue by zuoliwei** [Tencent/Firestorm#91]
hello, I tried in **MEMORY_HDFS** mode and reported the following error:

WARN shuffle.RssShuffleUtils: Empty conf items
ERROR shuffle.RssShuffleUtils: Storage path must be set by the client or fetched from coordinators.
ERROR spark.SparkContext: Error initializing SparkContext.
.
.
Caused by: java.lang.IllegalArgumentException: Storage path must be set by the client or fetched from coordinators.
	at org.apache.spark.shuffle.RssShuffleUtils.validateRssClientConf(RssShuffleUtils.java:220)
	at org.apache.spark.shuffle.RssShuffleManager.<init>(RssShuffleManager.java:154)
.

where  can i set the Storage path

**Comment by colinmjj** [comment]
@zuoliwei with HDFS mode，the following configuration should be set in both client and shuffle server：
client： `spark.rss.base.path hdfs://xxxxx`
shuffle server:  `rss.server.hdfs.base.path hdfs://xxxxxx`
with Memory_HDFS type, the performance of HDFS plays a key role to make RSS stable

**Comment by zuoliwei** [comment]
@colinmjj I edit the conf file as the following:

**server.conf**
`rss.rpc.server.port 19999
rss.jetty.http.port 19998
rss.storage.basePath hdfs://192.168.130.129:8020/Shuffle_data
rss.storage.type HDFS
rss.coordinator.quorum 192.168.130.131:19999
rss.server.buffer.capacity 1gb
rss.server.partition.buffer.size 150mb
rss.server.read.buffer.capacity 1gb
rss.server.flush.thread.alive 5
rss.server.flush.threadPool.size 10`

**spark-defaults.conf**
`spark.shuffle.manager            org.apache.spark.shuffle.RssShuffleManager
spark.rss.coordinator.quorum     192.168.130.131:19999
spark.rss.storage.type           HDFS
rss.storage.base.path            hdfs://192.168.130.129:8020/Shuffle_data`

but it does not work,  is there any mistakes？

**Comment by colinmjj** [comment]
please check my comments, in spark client, the name of configuration is `spark.rss.base.path`
BTW, Firestorm won't work well with HDFS, please try MEMORY_LOCAL_HDFS

**Comment by zuoliwei** [comment]
> please check my comments, in spark client, the name of configuration is `spark.rss.base.path` BTW, Firestorm won't work well with HDFS, please try MEMORY_LOCAL_HDFS

get，  thanks a lot！
